version: "3.1"

services:
  web:
    container_name: orderscounter_web
    build:
      context: ./docker/php-apache
    ports:
      - 80:80
    volumes:
      - ./application:/var/www/html/application:cached
      - ./assets:/var/www/html/assets:cached
      - ./system:/var/www/html/system:cached
      - ./index.php:/var/www/html/index.php:cached
      - ./.htaccess:/var/www/html/.htaccess:cached
    depends_on:
      - db

  db:
    image: mariadb:10.3
    container_name: orderscounter_db
    ports:
      - 3306:3306
    volumes:
      - ./orderscounter.sql:/docker-entrypoint-initdb.d/orderscounter.sql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ROOT_HOST: "%"
